import { writable } from "svelte/store";

export const drivers = writable([
  {
    number: 1,
    name: "Max Verstappen",
    value: "Max Verstappen",
    team: "Red Bull Racing",
    country: "Netherlands",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 11,
    name: "Sergio Pérez",
    value: "Sergio Pérez",
    team: "Red Bull Racing",
    country: "Mexico",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 44,
    name: "Lewis Hamilton",
    value: "Lewis Hamilton",
    team: "Mercedes",
    country: "United Kingdom",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 63,
    name: "George Russell",
    value: "George Russell",
    team: "Mercedes",
    country: "United Kingdom",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 16,
    name: "Charles Leclerc",
    value: "Charles Leclerc",
    team: "Ferrari",
    country: "Monaco",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 55,
    name: "Carlos Sainz",
    value: "Carlos Sainz",
    team: "Ferrari",
    country: "Spain",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 14,
    name: "Fernando Alonso",
    value: "Fernando Alonso",
    team: "Aston Martin",
    country: "Spain",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 18,
    name: "Lance Stroll",
    value: "Lance Stroll",
    team: "Aston Martin",
    country: "Canada",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 4,
    name: "Lando Norris",
    value: "Lando Norris",
    team: "McLaren",
    country: "United Kingdom",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },

  {
    number: 81,
    name: "Oscar Piastri",
    value: "Oscar Piastri",
    team: "McLaren",
    country: "Australia",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 31,
    name: "Esteban Ocon",
    value: "Esteban Ocon",
    team: "Alpine",
    country: "France",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 10,
    name: "Pierre Gasly",
    value: "Pierre Gasly",
    team: "Alpine",
    country: "France",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 23,
    name: "Alexander Albon",
    value: "Alexander Albon",
    team: "Williams",
    country: "Thailand",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 2,
    name: "Logan Sargeant",
    value: "Logan Sargeant",
    team: "Williams",
    country: "United States of America",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 27,
    name: "Nico Hulkenberg",
    value: "Nico Hulkenberg",
    team: "Haas",
    country: "Germany",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 20,
    name: "Kevin Magnussen",
    value: "Kevin Magnussen",
    team: "Haas",
    country: "Denmark",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 77,
    name: "Valtteri Bottas",
    value: "Valtteri Bottas",
    team: "Alfa Romeo",
    country: "Finland",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 24,
    name: "Zhou Guanyu",
    value: "Zhou Guanyu",
    team: "Alfa Romeo",
    country: "China",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 22,
    name: "Yuki Tsunoda",
    value: "Yuki Tsunoda",
    team: "Alpha Tauri",
    country: "Japan",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
  {
    number: 3,
    name: "Daniel Ricciardo",
    value: "Daniel Ricciardo",
    team: "Alpha Tauri",
    country: "Australia",
    image: "",
    points: 0,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    retirements: 0,
  },
]);
