name: CI
on:
  push:
    paths:
      - "api/**"
jobs:
  deploy:
    name: Deploy backend to Fly 🪰
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          cd api/
          flyctl deploy --remote-only -a formulaone
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
